Solution
mmikolajewski/RecipeApp pull request #1
Opened 2023-05-22 14:38 UTC by mmikolajewski

2023-05-28 10:03 UTC, slawekludwiczak requested changes
UWAGI OGÓLNE
W zadaniu głównym wyzwaniem jest praca z relacjami. U Ciebie co prawda istnieje relacja między Recipe i Author, ale nie ma opcji rejestracji, czy logowania, a przy dodawaniu przepisu nie ma możliwości wyboru autora. Osobiście usunąłbym z Twojej aplikacji autora, bo bez logowania i spring security ciężko tutaj sensownie to wykorzystać. Zamiast tego przerób RecipeCategory na klasę encji zamiast enuma i stwórz relację Recipe<>RecipeCategory.

W kodzie masz RecipeRepository i RecipeService. Jeżeli masz RecipeService, to tak naprawdę w kontrolerze nigdy nie powinieneś korzystać bezpośrednio z repozytorium. Cała logika, np. zwiększanie liczby polubień, powinna znajdować się w RecipeService. W tak prostej aplikacji akceptowalne jest pominięcie klasy RecipeService, wtedy w kontrolerze korzystaj po prostu z repozytorium i w nim umieść szczątkową logikę aplikacji.

DODAWANIE
W formularzu dodawania masz opcję wyboru grafiki, ale nie masz obsługi uploadu plików. To nie jest takie trywialne, więc albo ustawiaj losową grafikę, albo jakiś placeholder, albo jeżeli chcesz dodawać pliki, to możesz wzorować się na https://app.javastart.pl/kurs/spring/spr-projekt/lekcja/spring3-projekt-dodawanie-filmu
Masz też relację przepis<>autor, ale nie ma u Ciebie możliwości zakładania konta, czy logowania, więc nie do końca ma to sens, bo wszystkie nowe przepisy nie mają żadnego autora

EDYCJA
Podobne problemy dotyczą edycji, bo to prawie identyczny formularz. Tak naprawdę możesz obsługiwać dodawanie i edycję przy pomocy dokładnie tego samego formularza. Po prostu przy edycji id byłoby ustawione, a przy dodawaniu będzie puste

USUWANIE - OK

LISTA WSZYSTKICH - OK

WYŚWIETLANIE KATEGORII
Obsługujesz to zarówno pod adresem /list?category=... jak i /category i to w dwóch różnych kontrolerach. Wystarczy tylko ta druga opcja

WYŚWIETLANIE POJEDYNCZEGO PRZEPISU
Przydałby się tutaj też przycisk / link "Lubię to"

MOŻLIWOŚĆ KLIKNIĘCIA LUBIĘ TO
kod w kontrolerze do poprawy

NAJLEPSZE PRZEPISY - OK

WARSTWA WIZUALNA - OK

DANE TESTOWE
Dane testowe powinny być w pliku data.sql, albo import.sql
https://app.javastart.pl/kurs/spring/spring-data-dane-testowe/lekcja/spring3-data-dane-testowe-hibernate

UŻYTECZNOŚĆ
Uwagi wynikają głównie z wczesniejszych punktów. Masz relację z autorem, ale w formualrzu edycji i dodawania nie ma opcji jego wyboru (autor do usunięcia), podobnie masz poziom trudności i też nie ma możliwości jego wyboru. Nie masz uploadu plików, więc grafiki w nowych przepisach się nie ładują, kategorie obsługiwane są pod dwoma różnymi adresami.

Punktacja
możliwość dodawania nowego przepisu 0,5/1
możliwość edycji przepisu 0,5/1
możliwość usunięcia przepisu 1/1
wyświetlanie listy wszystkich przepisów 1/1
wyświetlanie przepisów według kategorii (każda strona kategorii oprócz listy przepisów powinna mieć krótki opis i jakiś obrazek wyróżniający) 0,5/1
wyświetlanie pojedynczego przepisu 0,8/1
możliwość kliknięcia "lubię to" przy przepisie 0,5/1
wyświetlanie listy najlepszych przepisów (tych, które mają najwięcej polubień) 1/1
Warstwa wizualna aplikacji 2/2
Przygotowanie danych testowych 0/1
Użyteczność aplikacji (intuicyjność) 0,5/1

Odejmuję też na razie punkty za błędy w kodzie i brak sensownej relacji na poziomie bazy danych.
Łącznie 7pkt

code review https://javastartbootcamp.slack.com/archives/C04ARV8BGAF/p1685268048567699

2023-05-28 10:03 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/controllers/RecipeController.java
> +            recipeRepository.delete(recipe);
Możesz wywołać metodę deleteById()

2023-05-28 10:03 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/controllers/RecipeController.java
> +        model.addAttribute("recipes", recipes);
Obsługę kategorii masz w CategoryController, więc nie rozumiem, po co tutaj w sumie ta sama opcja

2023-05-28 10:03 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/controllers/RecipeController.java
> +                       Model model, RedirectAttributes ra,
nieużywane parametry

2023-05-28 10:03 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/controllers/RecipeController.java
> +                       @PathVariable(value = "page", required = false)  String page) {
jeżeli chcesz przekierować do strony, z której przyszło żądanie, to lepiej użyć `@RequestHeader String referer`

2023-05-28 10:03 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/controllers/RecipeController.java
> +        return "redirect:/{page}";
Jeżeli przepis nie istnieje, to zamiast przekierowania, raczej powinna być strona błędu. Jeżeli masz klasę RecipeService, to w niej powinna być logika odpowiedzialna za zwiększanie polubień, a tutaj dosłownie 1 linijka `recipeService.likeRecipe(recipeId)`

2023-05-28 10:03 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/recipe/Recipe.java
> +import java.awt.*;
importy do usunięcia

2023-05-29 07:53 UTC, slawekludwiczak requested changes
Co do wyglądu, to więcej korzystaj z bootstrapa, mniej używaj własnych stylów. Przykładowo najlepiej wszystko umieszczać w nadrzędnym kontenerze z klasą `container`, która zapewnia automatycznie skalowane marginesy dla różnych wielkości ekranu.

Funkcjonalnie wszystko działa poza danymi testowymi. Do poprawy warstwa wizualna, trochę użyteczność i ogólna jakość kodu na poziomie klas (np. mieszanie kontrolera z service)

code review https://youtu.be/xhR8Cd1g8O8

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/recipe/Recipe.java
> +    @Lob
niepotrzebna adnotacja

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/resources/templates/add.html
> +          <label for="difficultyLevel" class="form-label">Kategoria</label>
Raczej poziom trudności

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/resources/templates/add.html
> +          <input placeholder="Imię Autora" type="text" class="form-control" id="Author" th:field="*{firstAndLastNameOfAuthor}">
Zgodnie z Twoją klasą Recipe, to imię i nazwisko, a nie samo imię

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/resources/templates/add.html
> +          <input type="text" id="imageAddress" name="imageAddress" th:field="*{imageAddress}" >
Dodaj klasę form-control

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/resources/templates/list.html
> +<h1 class="h1">LISTA <PRZEPISÓW></PRZEPISÓW></h1>
Błędna składnia

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/resources/templates/list.html
> +  </ul>
Na Twoim miejscu użyłbym tego elementu do prezentacji miniatur przepisów:
https://getbootstrap.com/docs/4.0/components/card/#card-decks

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/resources/templates/recipe.html
> +                    <h1 class="display-4 h1" th:text="|${recipe.name}|">Lorem ipsum nemipsum</h1>
Nie definiuj stylów w atrybucie style. Jeżeli korzystasz z bootstrapa, to najlepiej wcale nie używać własnych stylów, chyba, że naprawdę już nic się nie da wymyślić to umieść to w arkuszu stylów, a tutaj przypisz jedynie odpowiednią klasę do elementów

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/resources/templates/recipe.html
> +            <div style="margin-left: 200px; margin-right: 400px;" class="d-flex justify-content-center">
W tym szablonie mógłbyś sobie wykorzystać to:
https://bootsnipp.com/snippets/O54eO

Też tutaj opakuj wszystko w div z klasą container

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeController.java
> +        }
Na poziomie wyświetlania formularza przydałoby się akurat rozróżnić dwa adresy i dwie metody /add i /edit

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeController.java
> +    public String addRecipe(Recipe recipe) {
Tutaj możesz mieć wspólną logikę odpowiedzialną za zapis/aktualizację, ale w takiej sytuacji zmień raczej adres i nazwę metody na "save" - zarówno przy dodawaniu, jak i aktualizacji zapisujemy zmiany, więc ma to więcej sensu

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeService.java
> +        return "redirect:/list";
Warstwa usług nie powinna mieć pojęcia, gdzie będzie wykorzystywana. Nie powinieneś tutaj zwracać nazw widoków

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeService.java
> +            return "redirect:/e";
Warstwa usług nie powinna mieć pojęcia, gdzie będzie wykorzystywana. Nie powinieneś tutaj zwracać nazw widoków.
Jeżeli tutaj coś jest nie tak, to rzuć wyjątek

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeService.java
> +    public void addCategoryAtrubiteAndRecipeList(Model model, Long id) {
Nie przekazuj tutaj modelu, tylko zwróć to co potrzebujesz do kontrolera, a tam ustawiaj model

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/category/CategoryController.java
> +    public String home(Model model) {
home() sugeruje stronę główną, a do tego masz raczej osobny kontroler
Z tego co widzę, to ta metoda nie jest nigdy wykorzystywana

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/resources/templates/fragments.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></s
Masz tutaj jakąś inną wersję bootstrapa niż wyżej.
Skopiuj stąd
https://getbootstrap.com/docs/4.3/getting-started/download/

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/resources/templates/fragments.html
> +                        <a class="nav-link active" style="color: black" th:href="@{/category?id=4}" >Przekąski</a>
Nie ustawiaj stylów w kodzie html
Ponieważ kategorie mogą się zmieniać, być dodawane itp. to dobrze by było je pobierać z bazy i tutaj generować listę przez th:each.
Ustaw globalny atrybut modelu w sposób pokazany tutaj:
https://stackoverflow.com/questions/33876699/how-to-make-a-model-attribute-global

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/resources/templates/home.html
> +            <img class="recipeCard_img" th:src="${recipe.imageAddress}" />
Fajnie gdyby w obrazek też dało się kliknąć

2023-05-29 07:53 UTC, slawekludwiczak commented on src/main/resources/templates/home.html
> +            <a class="link" th:href="|@{/recipe?id=}${recipe.id}|">Zobacz</a></br>
Te linki są troche mało widoczne, najlepiej dodaj style, dzięki którym będzie to widzoczne jako przycisk

2023-06-03 19:23 UTC, marcinkunert requested changes
Bardzo ładnie to wygląda. Znalazłem trochę drobnostek do poprawy.

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/GlobalControllerAdvice.java
> +    private RecipeRepository recipeRepository;
Nieużywane pole

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/HomeController.java
> +    private CategoryRepository categoryRepository;
nieużywane pole, do usunięcia

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/RecipeAppApplication.java
> +        ConfigurableApplicationContext context = SpringApplication.run(RecipeAppApplication.class, args);
Nic nie robisz ze zmienną context, więc nie ma sensu jej tworzyć

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeRepository.java
> +    List<Recipe> findAll();
ta metoda istnieje domyśnie, nie trzeba jej dodawać

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/recipe/Recipe.java
> +    @Lob
@mmikolajewski nadal do poprawy

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/category/CategoryRepository.java
> +    List<Category> findAll();
ta metoda istnieje domyślnie, nie trzeba jej dodawać

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/category/Category.java
> +    private List<Recipe> recipes = new ArrayList<>();
Wydaje mi się, że `cascade = CascadeType.PERSIST` jest w tym przypadku niepotrzebne. Czy przy zapisie kategorii dodajesz jednocześnie do niej przepisy?

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeController.java
> +        }
formatowanie: za duże wcięcie

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeController.java
> +        return "/category";
niepotrzebny shash z przodu

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeService.java
> +    }
To przeniósłbym do CategoryService

2023-06-03 19:23 UTC, marcinkunert commented on src/main/resources/templates/add.html
> +          <select class="form-select" id="difficultyLevel" th:field="*{difficultyLevel}">
Z tego co widzę to klasa `form-select` jest z Bootstrapa 5, a w importach widziałem wersje 4.x.
Na razie ten select nie jest ostylowany. Możesz albo zastosować klasy z Boostrapa 4, albo zaimportowac boostrapa 5.

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeController.java
> +        return "add";
"add" używasz przy dodawaniu i edycji, zmień jego nazwę na coś bardziej pasującego

2023-06-03 19:23 UTC, marcinkunert commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeService.java
> +    }
Aktualnie wejście na przepis, który nie istnieje powoduje wyświetlenie stacktrace błedu w przeglądarce (/app/recipe?id=100). Lepiej rzucić tutaj dedykowany wyjątek, albo zwrócić Optional<Recipe> i odpowiednio to obsłużyc w kontrolerze

2023-06-05 12:24 UTC, slawekludwiczak requested changes

2023-06-05 12:24 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/GlobalControllerAdvice.java
> +@Controller
Niepotrzebna adnotacja

2023-06-05 12:24 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/HomeController.java
> +@ControllerAdvice
Adnotacji `ControllerAdvice` używamy w klasach, które są aspektami dla kontrolerów, nie w samych kontrolerach

2023-06-05 12:24 UTC, slawekludwiczak commented on src/main/java/pl/javastart/recipeapp/recipe/RecipeController.java
> +        return "add";
Nadal nie zmieniłeś, a lepiej by pasowało np. `recipe-form`

2023-08-13 17:38 UTC, merged